//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParsingMp3Tags {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParsingMp3Tags.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blues
        ///Classic Rock
        ///Country
        ///Dance
        ///Disco
        ///Funk
        ///Grunge
        ///Hip-Hop
        ///Jazz
        ///Metal
        ///New Age
        ///Oldies
        ///Other
        ///Pop
        ///R&amp;B
        ///Rap
        ///Reggae
        ///Rock
        ///Techno
        ///Industrial
        ///Alternative
        ///Ska
        ///Death Metal
        ///Pranks
        ///Soundtrack
        ///Euro-Techno
        ///Ambient
        ///Trip-Hop
        ///Vocal
        ///Jazz+Funk
        ///Fusion
        ///Trance
        ///Classical
        ///Instrumental
        ///Acid
        ///House
        ///Game
        ///Sound Clip
        ///Gospel
        ///Noise
        ///AlternRock
        ///Bass
        ///Soul
        ///Punk
        ///Space
        ///Meditative
        ///Instrumental Pop
        ///Instrumental Rock
        ///Ethnic
        ///Gothic
        ///Darkwave
        ///Techno-Industrial
        ///Electronic
        ///Pop-Folk
        ///Eurodance
        ///Dream
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DictionaryString {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
    }
}
